2019-10-23 19:30:28,190 ERROR: Exception on /login [GET] [in /home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dzhem/Documents/Projects/Miniblog/app/routes.py", line 51, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/dzhem/Documents/Projects/Miniblog/app/templates/login.html", line 2, in top-level template code
    {% from "_formhelpers.html" import render_field %}
  File "/home/dzhem/Documents/Projects/Miniblog/app/templates/base.html", line 36, in top-level template code
    {% block content %}{% endblock %}
  File "/home/dzhem/Documents/Projects/Miniblog/app/templates/login.html", line 17, in block "content"
    <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
2019-10-23 19:30:29,069 ERROR: Exception on /login [GET] [in /home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dzhem/Documents/Projects/Miniblog/app/routes.py", line 51, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/dzhem/Documents/Projects/Miniblog/app/templates/login.html", line 2, in top-level template code
    {% from "_formhelpers.html" import render_field %}
  File "/home/dzhem/Documents/Projects/Miniblog/app/templates/base.html", line 36, in top-level template code
    {% block content %}{% endblock %}
  File "/home/dzhem/Documents/Projects/Miniblog/app/templates/login.html", line 17, in block "content"
    <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/dzhem/Documents/Projects/Miniblog/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
